- name: Install software-properties-common (provides apt-add-repository)
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
    
- name: Enable Ubuntu Universe repository
  command: apt-add-repository universe

- name: Install curl if missing
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Get latest ros-apt-source release version from GitHub API
  ansible.builtin.uri:
    url: https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest
    return_content: yes
  register: ros_apt_release

- name: Set ROS_APT_SOURCE_VERSION fact
  set_fact:
    ros_apt_source_version: "{{ ros_apt_release.json.tag_name }}"

- name: Set OS version codename fact
  ansible.builtin.command: . /etc/os-release && echo $VERSION_CODENAME
  register: os_version_codename
  changed_when: false

- name: Download ros2-apt-source deb package
  get_url:
    url: "https://github.com/ros-infrastructure/ros-apt-source/releases/download/{{ ros_apt_source_version }}/ros2-apt-source_{{ ros_apt_source_version }}.{{ os_version_codename.stdout }}_all.deb"
    dest: /tmp/ros2-apt-source.deb

- name: Install ros2-apt-source deb package
  apt:
    deb: /tmp/ros2-apt-source.deb

- name: Update packages
  command: apt update && apt upgrade -y

- name: ROS-Base Install (Bare Bones) - Communication libraries, message packages, command line tools. No GUI tools.
  command: apt install -y ros-kilted-ros-base

- name: Source ROS 2 setup script
  ansible.builtin.shell: echo "source /opt/ros/kilted/setup.bash" >> /home/{{ ansible_user }}/.bashrc
  args:
    executable: /bin/bash