services:
  rpi-camera:
    container_name: rpi-camera
    # build:
    #   context: .
    #   dockerfile: ./deploy/Dockerfile
    image: vvasylkovskyi1/rpi-camera:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    ports:
      - "8080:8080"
