- name: Install cloudflared binary
  command: >
    wget -O /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm
  args:
    creates: /usr/local/bin/cloudflared

- name: Make cloudflared executable
  command: chmod +x /usr/local/bin/cloudflared

- name: Install Cloudflare Tunnel service using token
  command: cloudflared service install {{ cloudflare_tunnel_token }}
  args:
    creates: /etc/systemd/system/cloudflared.service

- name: Enable cloudflared service to start on boot
  command: systemctl enable cloudflared

- name: Start cloudflared service
  command: systemctl start cloudflared

- name: Verify cloudflared version
  command: cloudflared --version
  register: cloudflared_version

- name: Show cloudflared version
  debug:
    var: cloudflared_version.stdout
