- name: Update package list
  command: apt update

- name: Upgrade all packages
  command: apt upgrade -y

- name: Install Python 3 and pip
  apt:
    name:
      - python3
      - python3-pip
    state: latest
    update_cache: yes