services:
  video-service-web:
    container_name: video-service-web
    build:
      context: .
      dockerfile: ./Dockerfile
  #   # image: vvasylkovskyi1/vvasylkovskyi-video-service-web:latest
  #   # restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    env_file:
      - .env
    # ports:
    #   - '4000:4000'
    #   - '4001:4001/udp'
    network_mode: "host" 
    
networks:
  app-network:
    driver: bridge
    name: app-network
