services:
  video-service-web:
    container_name: video-service-web
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
  #   # image: vvasylkovskyi1/vvasylkovskyi-video-service-web:latest
  #   # restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    env_file:
      - .env
    ports:
      - '8080:8080'

networks:
  app-network:
    driver: bridge
    name: app-network
