- name: Ensure .ssh directory exists
  file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    owner: "{{ rpi_user }}"
    group: "{{ rpi_user }}"
    mode: '0700'

- name: Generate SSH key pair if it doesn't exist
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: rsa
    size: 2048
    owner: "{{ rpi_user }}"
    group: "{{ rpi_user }}"
    mode: '0600'
  register: keygen_result

- name: Read public key from Raspberry Pi
  slurp:
    src: "{{ ssh_key_path }}.pub"
  register: public_key_contents

- name: Decode public key
  set_fact:
    public_key: "{{ public_key_contents.content | b64decode }}"

- name: Save public key to local file for Terraform
  copy:
    content: "{{ public_key }}"
    dest: "{{ local_pubkey_path }}"
  delegate_to: localhost
  become: false