
- name: Update apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install required packages
  apt:
    name:
      - git
      - docker.io
      - curl
      - jq
    state: present

- name: Create runner directory
  file:
    path: "{{ runner_dir }}"
    state: directory
    owner: "{{ rpi_user }}"
    group: "{{ rpi_user }}"

- name: Download GitHub Actions runner tarball
  become_user: "{{ rpi_user }}"
  get_url:
    url: "https://github.com/actions/runner/releases/download/v{{ runner_version }}/actions-runner-linux-arm64-{{ runner_version }}.tar.gz"
    dest: "{{ runner_dir }}/actions-runner.tar.gz"
    mode: '0644'

- name: Extract GitHub Actions runner
  become_user: "{{ rpi_user }}"
  unarchive:
    src: "{{ runner_dir }}/actions-runner.tar.gz"
    dest: "{{ runner_dir }}"
    remote_src: yes

- name: Configure GitHub Actions runner
  become_user: "{{ rpi_user }}"
  shell: |
    ./config.sh --unattended --url {{ github_repo_url }} --token {{ runner_token }} --labels {{ runner_labels }} --work _work
  args:
    chdir: "{{ runner_dir }}"
  register: config_output
  changed_when: "'Runner successfully configured' in config_output.stdout"

- name: Install runner as a service
  become_user: "{{ rpi_user }}"
  shell: |
    sudo ./svc.sh install
    sudo ./svc.sh start
  args:
    chdir: "{{ runner_dir }}"
