# === Install Docker on Raspberry Pi ===

- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Install Docker using official convenience script
  shell: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add current user to docker group
  user:
    name: "{{ ansible_user | default('pi') }}"
    groups: docker
    append: yes


- name: Show Docker version
  command: docker --version
  register: docker_version

- name: Show Docker Compose version (v2 plugin)
  command: docker compose version
  register: docker_compose_version

- name: Display Docker version
  debug:
    var: docker_version.stdout

- name: Display Docker Compose version
  debug:
    var: docker_compose_version.stdout

- name: Run Docker container with restart policy
  become: yes
  shell: |
    docker rm -f myapp || true
    docker run -d --restart unless-stopped -p 80:80 vvasylkovskyi1/vvasylkovskyi-portfolio:latest
  args:
    executable: /bin/bash