- name: Upgrade all packages
  shell: apt update && apt full-upgrade -y

# - name: Install IMX500 firmware
#   apt:
#     name: imx500-all
#     state: present
#     update_cache: yes

- name: Install Picamera2
  apt:
    name: python3-picamera2
    state: present

- name: Install FFMPEG
  apt:
    name: ffmpeg
    state: present
