- name: Setup Raspberry Pi 
  hosts: all
  become: true
  vars_files:
    - ../secrets.yml

  vars:
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_site: "datadoghq.eu"
    github_repo_url: "https://github.com/vvasylkovskyi/rpi-camera"
    runner_token: "AGFCS3IVCOEXAQOIIO4TXC3IM2H3S"
    runner_version: "2.315.0"
    runner_labels: "rpi,arm64,docker"
    runner_dir: "/home/vvasylkovskyi/actions-runner" 
    runner_user: "vvasylkovskyi"       
    docker_username: "{{ docker_username }}"

  roles:
    # - setup
    # - datadog
    # - docker
    # - camera_imx500
    # - promote_to_github_runner
    - docker_start_container_on_boot
    # - reboot