name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: "Deploy Rpi Product App"
        required: true

jobs:
  rpi_product_app_build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Container Image
        run: |
          TAG=${{ github.sha }}
          echo "Using tag: $TAG"
          docker build -f ./deploy/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/rpi-product-app:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/rpi-product-app:$TAG

  update_terraform_vars:
    runs-on: ubuntu-latest
    needs: rpi_product_app_build_and_push
    steps:
      - name: Checkout infra repo
        run: |
          git clone https://x-access-token:${{ secrets.INFRA_REPO_PAT }}@github.com/vvasylkovskyi/vvasylkovskyi-infra.git

      - name: Update docker_image_hash_rpi_product_app in terraform.tfvars
        run: |
          cd vvasylkovskyi-infra/apps/portfolio
          FILE=terraform.tfvars
          TAG=${{ needs.rpi_product_app_build_and_push.outputs.image_tag }}
          echo "Replacing docker_image_hash_rpi_product_app with: $TAG"
          sed -i -E "s|(^\s*docker_image_hash_rpi_product_app\s*=\s*\")[^\"]*(\".*)|\1$TAG\2|" $FILE
          echo "--- Resulting terraform.tfvars ---"
          cat $FILE

      - name: Commit and push changes
        run: |
          cd vvasylkovskyi-infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add apps/portfolio/terraform.tfvars
            git commit -m "Update docker_image_hash_rpi_product_app to ${{ needs.rpi_product_app_build_and_push.outputs.image_tag }}"
            git push origin main
          fi
