name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      inputs:
      version:
        description: "Deploy vvasylkovskyi Video Service"
        required: true

jobs:
  video_service_web_build_and_push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Container Image
        run: |
          TAG=${{ github.sha }}
          echo "Using tag: $TAG"
          docker build -f ./video-service-web/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-video-service-web:$TAG ./video-service-web
          docker push ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-video-service-web:$TAG

      - name: Set output tag
        id: set_tag
        run: echo "tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  update_terraform_vars:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout portfolio repo
        run: |
          git clone https://x-access-token:${{ secrets.PORTFOLIO_REPO_PAT }}@github.com/vvasylkovskyi/vvasylkovskyi-portfolio.git

      - name: Update docker_image_hash_video_service in terraform.tfvars
        run: |
          cd vvasylkovskyi-portfolio/infra/terraform
          FILE=terraform.tfvars
          TAG=${{ needs.build_and_push.outputs.tag }}
          echo "Replacing docker_image_hash_video_service with: $TAG"
          sed -i -E "s|(^\s*docker_image_hash_video_service\s*=\s*\")[^\"]*(\".*)|\1$TAG\2|" $FILE
          echo "--- Resulting terraform.tfvars ---"
          cat $FILE

      - name: Commit and push changes
        run: |
          cd vvasylkovskyi-portfolio
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add infra/terraform/terraform.tfvars
          git commit -m "Update docker_image_hash_video_service to ${{ needs.build_and_push.outputs.tag }}"
          git push origin main
