- name: Create systemd service to start latest docker container at boot
  become: yes
  copy:
    dest: /etc/systemd/system/rpi-camera.service
    content: |
      [Unit]
      Description=Start latest rpi-camera Docker container
      After=docker.service
      Requires=docker.service

      [Service]
      Type=oneshot
      RemainAfterExit=true
      ExecStartPre=-/usr/bin/docker stop rpi-camera
      ExecStartPre=-/usr/bin/docker rm rpi-camera
      ExecStartPre=/usr/bin/docker pull {{ docker_username }}/rpi-camera
      ExecStart=/usr/bin/docker run -d --name rpi-camera --restart unless-stopped -p {{ local_port }}:{{ local_port }} {{ docker_username }}/rpi-camera

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  become: yes
  systemd:
    daemon_reload: yes

- name: Enable rpi-camera service to start on boot
  become: yes
  systemd:
    name: rpi-camera
    enabled: yes
    state: started

- name: Restart reverse SSH tunnel
  systemd:
    name: "rpi-camera"
    state: restarted